# zbgw8201.yaml
esphome:
  name: zbgw8201
  project: 
    name: dongszb.zigbee-gateway
    version: "1.0"

dashboard_import:
  package_import_url: github://dongbh/zbgw8201/zbgw8201.yaml

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

external_components:
#  - source: github://oxan/esphome-stream-server
#  - source: github://dongbh/esphome-stream-server
#  - source: github://tube0013/esphome-stream-server-v2
  - source: github://dongbh/esphome-stream-server-v2

ethernet:
  type: RTL8201
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
  power_pin: GPIO17

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Esphome Zb Bridge"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 1h
ota:

#web_server:
#  port: 80

uart:
  id: uart_bus
  tx_pin: GPIO33
  rx_pin: GPIO32
#  rx_buffer_size: 1024
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: ss
  port: 6636
#  buffer_size: 2048

binary_sensor:
  - platform: homeassistant
    id: ble_gateway_discovery
    entity_id: binary_sensor.ble_gateway
  - platform: stream_server
    stream_server: ss
    name: Connected
    id: connected
    on_state:
      then:
        - lambda: |-
            if (id(connected).state) {
              id(yellow_led).turn_on();
            } else {
              id(yellow_led).turn_off();
            }

sensor:
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

status_led:
  pin: 
    number: GPIO14
    inverted: true

switch:
#  - platform: gpio
#    pin: 14
#    id: green_led
#    inverted: true
  - platform: gpio
    pin: 4
    id: yellow_led
    name: Yellow_LED
    inverted: true
    internal: true
  - platform: gpio
    pin: 16
    id: blue_led
    name: Blue_LED
    inverted: true
 

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true